# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MVVM' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Parsing
  pod 'ObjectMapper', '~> 2.2'
  
  # Network Calls
  pod 'Alamofire', '~> 4.5'



  target 'MVVMTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MVVMUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
